//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResidentialExpenses.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResidentialExpenses.Exceptions.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail já registrado..
        /// </summary>
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail não pode ser vazio..
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail inválido..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail e/ou senha inválidos.
        /// </summary>
        public static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida..
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode ser vazio..
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido..
        /// </summary>
        public static string UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_ERROR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Token de autenticação não fornecido..
        /// </summary>
        public static string NO_TOKEN {
            get {
                return ResourceManager.GetString("NO_TOKEN", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Token de autenticação expirado..
        /// </summary>
        public static string TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sem permissão para acessar este recurso..
        /// </summary>
        public static string USER_WITHOUT_PERMISSION_ACCESS_RESOURCE {
            get {
                return ResourceManager.GetString("USER_WITHOUT_PERMISSION_ACCESS_RESOURCE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A senha atual está incorreta..
        /// </summary>
        public static string OLD_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("OLD_PASSWORD_INCORRECT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O nome da pessoa não pode ser vazio..
        /// </summary>
        public static string PERSON_NAME_EMPTY {
            get {
                return ResourceManager.GetString("PERSON_NAME_EMPTY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A idade deve ser maior que zero..
        /// </summary>
        public static string PERSON_AGE_INVALID {
            get {
                return ResourceManager.GetString("PERSON_AGE_INVALID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pessoa não encontrada..
        /// </summary>
        public static string PERSON_NOT_FOUND {
            get {
                return ResourceManager.GetString("PERSON_NOT_FOUND", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A descrição da categoria não pode ser vazia..
        /// </summary>
        public static string CATEGORY_DESCRIPTION_EMPTY {
            get {
                return ResourceManager.GetString("CATEGORY_DESCRIPTION_EMPTY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A finalidade da categoria é inválida..
        /// </summary>
        public static string CATEGORY_PURPOSE_INVALID {
            get {
                return ResourceManager.GetString("CATEGORY_PURPOSE_INVALID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A descrição da transação não pode ser vazia..
        /// </summary>
        public static string TRANSACTION_DESCRIPTION_EMPTY {
            get {
                return ResourceManager.GetString("TRANSACTION_DESCRIPTION_EMPTY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O valor da transação deve ser maior que zero..
        /// </summary>
        public static string TRANSACTION_VALUE_MUST_BE_POSITIVE {
            get {
                return ResourceManager.GetString("TRANSACTION_VALUE_MUST_BE_POSITIVE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O tipo da transação é inválido..
        /// </summary>
        public static string TRANSACTION_TYPE_INVALID {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_INVALID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Categoria não encontrada..
        /// </summary>
        public static string TRANSACTION_CATEGORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("TRANSACTION_CATEGORY_NOT_FOUND", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A categoria informada não é compatível com o tipo da transação..
        /// </summary>
        public static string TRANSACTION_CATEGORY_PURPOSE_MISMATCH {
            get {
                return ResourceManager.GetString("TRANSACTION_CATEGORY_PURPOSE_MISMATCH", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menores de 18 anos só podem ter transações do tipo despesa..
        /// </summary>
        public static string TRANSACTION_MINOR_ONLY_EXPENSE {
            get {
                return ResourceManager.GetString("TRANSACTION_MINOR_ONLY_EXPENSE", resourceCulture);
            }
        }
    }
}
